Add round-digits option to have better image compression
mapbox/rio-rgbify pull request #34
Opened 2021-11-22 13:58 UTC by frodrigo

# In short

Add an option to arbitrary round the encoded elevation value. Switch to 0 an arbitrary number of lower digit to reduce the noise into the RGB encoded image.
Less noise achieves a better compression.
It has the counter part to approximate the encoded elevation.

For low zoom level (like 8) the elevation change between pixel is hight, but the elevation precision required at this overview level is low. We can erase lot of lower digits and have high compression gain.

At upper zoom (like 12), the noise on lower digits is lesser. But we can still save space by round some few lower bits.

# Long version

An original tile of z8. 430 KB.

![rio-rgbify-04-z8-92](https://user-images.githubusercontent.com/1785486/142873977-0b21fb85-844e-42e6-b556-4c4c949a0a46.png)

If we look at the different colors separately of a level 8 tile, we can clearly see that red does not vary, green varies little and blue a lot.

Decomposition of the levels of Red, Green and Blue. Note that the first one is indeed "red", but very dark, uniform value: 1 out of 255.

![rio-rgbify-08-ChannelRGB](https://user-images.githubusercontent.com/1785486/142873683-ddf2da1b-8514-4f22-bcb2-a8ea4fb90975.png)

It can be seen that the Blue channel is much noisier than the others, especially for low zoom levels where the altitude varies a lot from one pixel to its neighbors, almost at random. If we delete the blue channel (we can't really delete it, but set the value to 0 for all pixels) then the same image compressed in PNG is only 91 Kb, or 80% less. Tthis very noisy data that makes the image difficult to compress. The more random the values are, the greater the entropy, and therefore the ineffective compression.

Tile at zoom level 8 containing 0 for the blue value. 97 Kb, or 77% less.

![rio-rgbify-09-z8-92RG](https://user-images.githubusercontent.com/1785486/142873736-15dd91c3-e21a-4593-a05e-319a03835954.png)

Tile with zoom level 12 containing 0 for the blue value. 41 KB, or 87% less.

![rio-rgbify-10-z12-1484RG](https://user-images.githubusercontent.com/1785486/142873796-42997e4a-65cf-451a-b384-f6301186ec21.png)

The blue channel has an amplitude of 256 levels, one level represents 10 cm. We have therefore introduced a maximum error of 256 * 0.1 = 25.6 m in altitude.

For example, at a zoom level of 8, the horizontal difference between two pixels is 431 m, an altimetry error of 25 m may be acceptable.

Animation showing the shading at zoom 8 before and after changing the values stored in the blue to 0. Having trouble seeing the animation? That's a good sign!

![rio-rgbify-11-diff-optim](https://user-images.githubusercontent.com/1785486/142873826-5fd7368a-3099-45d4-87fb-e604a4bce688.gif)

The same area with an extract enlarged x4 to see better what's going on.

![rio-rgbify-12-diff-optim_x4](https://user-images.githubusercontent.com/1785486/142873855-8575080e-85d2-4762-aa5a-edadfb440760.gif)

Differences in shading values before and after modification.

![rio-rgbify-13-diff](https://user-images.githubusercontent.com/1785486/142873880-b4971932-cf43-4fe6-a9fb-5a2ee4e21a8c.png)

Removing the blue-encoded part is in fact equivalent to rounding the altitude to the nearest 25 m and setting the last 8 bits (the bits encoded in blue) to 0. This can be extended by varying the level of precision on which the altitude is rounded and therefore the number of last bits that are set to 0 depending on the zoom level.

The processing of the French DEM at horizon precision of 25m to z5 up to z12 produce an 1.3 GB in PNG instead of 3.7, which is a 65% reduction in size, and 0.8 GB in WebP instead of 2.2 GB, which is also a 65% reduction in size. Using a ramp of rounding precision from 11 digits à z5 down to 4 digits at z12.

2022-01-11 13:47 UTC, frodrigo commented
Read the full story at https://medium.com/@frederic.rodrigo/optimization-of-rgb-dem-tiles-for-dynamic-hill-shading-with-mapbox-gl-or-maplibre-gl-55bef8eb3d86

2022-01-11 16:04 UTC, dnomadb requested changes
This looks good! Just one suggestion on adding this as an option not an argument.

The approach is similar to how we've optimized our terrain data for 3d:
- https://www.mapbox.com/blog/mapbox-gl-js-v2-3d-maps-camera-api-sky-api-launch
- https://www.mapbox.com/blog/realistic-3d-experience

2022-01-11 16:04 UTC, dnomadb commented on rio_rgbify/encoders.py
> +def data_to_rgb(data, baseval, interval, round_digits):
I think this should be an option:
```
def data_to_rgb(data, baseval, interval, round_digits=0):

```

2022-01-11 16:31 UTC, frodrigo commented on rio_rgbify/encoders.py
> +def data_to_rgb(data, baseval, interval, round_digits):
You are right. Done.

2022-01-11 16:32 UTC, dnomadb approved these changes

2022-01-11 16:33 UTC, dnomadb commented
Thanks again @frodrigo ! I'll get this merged and pushed to pypi first thing tomorrow.

2022-04-08 20:36 UTC, merged

2022-04-10 16:53 UTC, systemed commented
Thank you! (Especially as I gather it was your last day at Mapbox!)